# Coursera_Capstone_Project_Example

### This Notebook is mainly used for Capstone Project.

In [1]:
import numpy as np
import pandas as pd

In [10]:
print("Hello Capstone Project Course!")

Hello Capstone Project Course!


In [4]:
a = np.arange(20).reshape(4,5)
print (a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [7]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype.name)

(4, 5)
2
20
int32


In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
df = pd.DataFrame({'Name': ['Himanshu','Anshu','Sachin','Suman'], 'Branch': ['CSE','EEE','IT','ME']})
df

Name Branch
0  Himanshu    CSE
1     Anshu    EEE
2    Sachin     IT
3     Suman     ME

### That's enough for basic ideas about related to this notebook....